### PR TITLE
Fix AD issue with mixed input for TransformedKernel

### LINKED ISSUE #151: AD issue with mixed inputs
MWE : 
```julia
using KernelFunctions, Flux
k = transform(SqExponentialKernel(), 10.0)
x = rand(5, 3)
X = collect(eachcol(x))
Y = KernelFunctions.ColVecs(x)
kernelmatrix(k, X, Y) # Works!
gradient(Flux.params(k)) do 
sum(kernelmatrix(k, X, Y))
end

ERROR: In slow method
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::KernelFunctions.var"#back#143")(::Array{Array{Float64,1},1}) at /home/theo/.julia/dev/KernelFunctions/src/zygote_adjoints.jl:66
 [3] (::KernelFunctions.var"#1277#back#144"{KernelFunctions.var"#back#143"})(::Array{Array{Float64,1},1}) at /home/theo/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [4] _map at /home/theo/.julia/dev/KernelFunctions/src/transform/scaletransform.jl:23 [inlined]
 [5] (::typeof(∂(_map)))(::Array{Array{Float64,1},1}) at /home/theo/.julia/packages/Zygote/iFibI/src/compiler/interface2.jl:0
 [6] kernelmatrix at /home/theo/.julia/dev/KernelFunctions/src/kernels/transformedkernel.jl:91 [inlined]
 [7] (::typeof(∂(kernelmatrix)))(::FillArrays.Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}) at /home/theo/.julia/packages/Zygote/iFibI/src/compiler/interface2.jl:0
...
```

In comparison

```julia
gradient(Flux.params(k)) do 
sum(kernelmatrix(k, X, X))
end
```
or
```julia
gradient(Flux.params(k)) do 
sum(kernelmatrix(k, Y, Y))
end
```

work fine.

### PR DESCRIPTION
**Pull request by sharanry**
Fix #151

### CODE REVIEW

**Comment by devmotion** [comment]
I don't think this fixes the actual problem, IMO we shouldn't have to handle and convert `ColVecs` and `RowVecs` inputs here. Could it be that it's just missing a `vec_of_vecs` definition for `ColVecs` and `RowVecs` or an adjoint for `_map`?

**Comment by sharanry** [comment]
> I don't think this fixes the actual problem, IMO we shouldn't have to handle and convert `ColVecs` and `RowVecs` inputs here. Could it be that it's just missing a `vec_of_vecs` definition for `ColVecs` and `RowVecs` or an adjoint for `_map`?

The transform `map` is applied individually to each input IIRC. So, I don't think it should cause a problem  The problem is when executing the pullback function using the common result as a reference. Maybe defining adjoint for `kernelmatrix` of TransformedKernel should help? Isn't that where the inputs are combined to form a single output.

**Comment by devmotion** [comment]
This shows that the problem is not caused by `kernelmatrix`:
```julia
julia> Zygote.gradient() do
           sum(sum(KernelFunctions._map(k.transform, X)))
       end
()

julia> Zygote.gradient() do
           sum(sum(KernelFunctions._map(k.transform, Y)))
       end
ERROR: In slow method
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::KernelFunctions.var"#back#173")(::FillArrays.Fill{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},1,Tuple{Base.OneTo{Int64}}}) at /home/david/.julia/dev/KernelFunctions/src/zygote_adjoints.jl:66
 [3] (::KernelFunctions.var"#159#back#174"{KernelFunctions.var"#back#173"})(::FillArrays.Fill{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},1,Tuple{Base.OneTo{Int64
}}}) at /home/david/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [4] _map at /home/david/.julia/dev/KernelFunctions/src/transform/scaletransform.jl:25 [inlined]
 [5] (::typeof(∂(_map)))(::FillArrays.Fill{FillArrays.Fill{Float64,1,Tuple{Base.OneTo
{Int64}}},1,Tuple{Base.OneTo{Int64}}}) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface2.jl:0
 [6] #17 at ./REPL[25]:2 [inlined]
 [7] (::typeof(∂(#17)))(::Float64) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface2.jl:0
 [8] (::Zygote.var"#41#42"{typeof(∂(#17))})(::Float64) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface.jl:45
 [9] gradient(::Function) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface.jl:54
 [10] top-level scope at REPL[25]:1
```

**Comment by devmotion** [comment]
Or `_map`:
```julia
julia> Zygote.gradient(rand(3, 3)) do x
           sum(sum(KernelFunctions.ColVecs(x)))
       end
ERROR: In slow method
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::KernelFunctions.var"#back#173")(::FillArrays.Fill{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},1,Tuple{Base.OneTo{Int64}}}) at /home/david/.julia/dev/KernelFunctions/src/zygote_adjoints.jl:66
 [3] (::KernelFunctions.var"#159#back#174"{KernelFunctions.var"#back#173"})(::FillArrays.Fill{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},1,Tuple{Base.OneTo{Int64}}}) at /home/david/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [4] #29 at ./REPL[30]:2 [inlined]
 [5] (::typeof(∂(#29)))(::Float64) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface2.jl:0
 [6] (::Zygote.var"#41#42"{typeof(∂(#29))})(::Float64) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface.jl:45
 [7] gradient(::Function, ::Array{Float64,2}) at /home/david/.julia/packages/Zygote/rqvFi/src/compiler/interface.jl:54
 [8] top-level scope at REPL[30]:1
```

**Comment by devmotion** [comment]
I guess here the problem might be that it falls back to https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/0e3ed6d3c253ab69f8066758907dcd938977815a/src/distances/pairwise.jl#L3 for mixed inputs.

File: src/utils.jl [hunk 1]
```diff
@@ -43,6 +43,8 @@ dim(x::ColVecs) = size(x.X, 1)
 
 pairwise(d::PreMetric, x::ColVecs) = Distances.pairwise(d, x.X; dims=2)
 pairwise(d::PreMetric, x::ColVecs, y::ColVecs) = Distances.pairwise(d, x.X, y.X; dims=2)
+pairwise(d::PreMetric, x::AbstractVector, y::ColVecs) = Distances.pairwise(d, reduce(hcat, x), y.X; dims=2)
+pairwise(d::PreMetric, x::ColVecs, y::AbstractVector) = Distances.pairwise(d, x.X, reduce(hcat, y); dims=2)
```
Comment (sharanry) [inline src/utils.jl:47]: @devmotion Thanks for that!

I think this fixes the problem. But I am not sure if this is the right way to go about it. Is this better than the slow method?

File: src/utils.jl [hunk 2]
```diff
@@ -73,6 +75,8 @@ dim(x::RowVecs) = size(x.X, 2)
 
 pairwise(d::PreMetric, x::RowVecs) = Distances.pairwise(d, x.X; dims=1)
 pairwise(d::PreMetric, x::RowVecs, y::RowVecs) = Distances.pairwise(d, x.X, y.X; dims=1)
+pairwise(d::PreMetric, x::AbstractVector, y::RowVecs) = Distances.pairwise(d, transpose(hcat(x...)), y.X; dims=1)
+pairwise(d::PreMetric, x::RowVecs, y::AbstractVector) = Distances.pairwise(d, x.X, transpose(hcat(y...)); dims=1)
```
Comment (devmotion) [inline src/utils.jl]:
```suggestion
function pairwise(d::PreMetric, x::AbstractVector, y::RowVecs)
    return Distances.pairwise(d, permutedims(reduce(hcat, x)), y.X; dims=1)
end
function pairwise(d::PreMetric, x::RowVecs, y::AbstractVector)
    return Distances.pairwise(d, x.X, permutedims(reduce(hcat, y)); dims=1)
end
```
Alternatively, one could fall back to the generic implementation in this case:
```suggestion
pairwise(d::PreMetric, x::AbstractVector, y::RowVecs) = pairwise(d, x, collect(y))
pairwise(d::PreMetric, x::RowVecs, y::AbstractVector) = pairwise(d, collect(x), y)
```

File: src/utils.jl [hunk 3]
```diff
@@ -75,8 +79,12 @@ dim(x::RowVecs) = size(x.X, 2)
 
 pairwise(d::PreMetric, x::RowVecs) = Distances.pairwise(d, x.X; dims=1)
 pairwise(d::PreMetric, x::RowVecs, y::RowVecs) = Distances.pairwise(d, x.X, y.X; dims=1)
-pairwise(d::PreMetric, x::AbstractVector, y::RowVecs) = Distances.pairwise(d, transpose(reduce(hcat, x)), y.X; dims=1)
-pairwise(d::PreMetric, x::RowVecs, y::AbstractVector) = Distances.pairwise(d, x.X, transpose(reduce(hcat, y)); dims=1)
+function pairwise(d::PreMetric, x::AbstractVector, y::RowVecs)
+    return Distances.pairwise(d, transpose(reduce(hcat, x)), y.X; dims=1)
```
Comment (devmotion) [inline src/utils.jl:83]: Just noticed, I guess `permutedims` is more appropriate here since we do not want to apply it recursively:
```suggestion
    return Distances.pairwise(d, permutedims(reduce(hcat, x)), y.X; dims=1)
```

File: src/utils.jl [hunk 4]
```diff
@@ -75,8 +79,12 @@ dim(x::RowVecs) = size(x.X, 2)
...
+end
+function pairwise(d::PreMetric, x::RowVecs, y::AbstractVector)
+    return Distances.pairwise(d, x.X, transpose(reduce(hcat, y)); dims=1)
```
Comment (devmotion) [inline src/utils.jl:86]: Same here:
```suggestion
    return Distances.pairwise(d, x.X, permutedims(reduce(hcat, y)); dims=1)
```

File: src/utils.jl (hunk 1 above)
Comment (devmotion) [reply src/utils.jl]: IMO users should never specify mixed inputs but it's good to handle the case. Since it's not the intended use case I guess it is fine to stack the data into a matrix. Alternatively, one could convert `ColVecs` to a vector of views and use the `broadcast` fallback.

**Review by devmotion — APPROVED** [review]

**Comment by devmotion** [comment]
Oh I forgot - we should bump the patch version such that we can make a new release @sharanry
