### PR TITLE
fix Distances compat

### LINKED ISSUE #390: Distances 0.10.5 breaks tests
Following this PR : https://github.com/JuliaStats/Distances.jl/pull/221 and release (0.10.5), our "Others" started to fail.
In https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/381, the compat limit is set to 0.10.4 so tests can pass, but we should solve this issue at some point.

Error looks like:
```julia
Chain Rules: Error During Test at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/chainrules.jl:1
  Got exception outside of a @test
  Compiling Tuple{Distances.var"#SqMahalanobis#7#8",Bool,Type{SqMahalanobis},Array{Float64,2}}: try/catch is not supported.
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] instrument(::IRTools.Inner.IR) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/reverse.jl:121
   [3] #Primal#20 at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/reverse.jl:202 [inlined]
   [4] Type at ./none:0 [inlined]
   [5] #Adjoint#36(::Nothing, ::Bool, ::Type{Zygote.Adjoint}, ::IRTools.Inner.IR) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/reverse.jl:315
   [6] (::Core.var"#kw#Type")(::NamedTuple{(:varargs, :normalise),Tuple{Nothing,Bool}}, ::Type{Zygote.Adjoint}, ::IRTools.Inner.IR) at ./none:0
   [7] _generate_pullback_via_decomposition(::Type) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/emit.jl:101
   [8] #s2974#1192 at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface2.jl:28 [inlined]
   [9] #s2974#1192(::Any, ::Any, ::Any, ::Any) at ./none:0
   [10] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:524
   [11] SqMahalanobis at /home/runner/.julia/packages/Distances/1OMiQ/src/mahalanobis.jl:57 [inlined]
   [12] _pullback(::Zygote.Context, ::Type{SqMahalanobis}, ::Array{Float64,2}) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface2.jl:0
   [13] #232 at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/chainrules.jl:25 [inlined]
   [14] _pullback(::Zygote.Context, ::var"#232#238", ::Array{Array{Float64,N} where N,1}) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface2.jl:0
   [15] _pullback(::Function, ::Array{Array{Float64,N} where N,1}) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface.jl:34
   [16] pullback(::Function, ::Array{Array{Float64,N} where N,1}) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface.jl:40
   [17] gradient(::Function, ::Array{Array{Float64,N} where N,1}) at /home/runner/.julia/packages/Zygote/rv6db/src/compiler/interface.jl:75
   [18] gradient(::Function, ::Val{:Zygote}, ::Array{Array{Float64,N} where N,1}) at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/test_utils.jl:48
   [19] gradient(::Function, ::Symbol, ::Array{Array{Float64,N} where N,1}) at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/test_utils.jl:45
   [20] compare_gradient(::Function, ::Symbol, ::Array{Array{Float64,N} where N,1}) at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/test_utils.jl:73
   [21] top-level scope at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/chainrules.jl:24
   [22] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107
   [23] top-level scope at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/chainrules.jl:2
   [24] include at ./boot.jl:328 [inlined]
   [25] include_relative(::Module, ::String) at ./loading.jl:1105
   [26] include(::Module, ::String) at ./Base.jl:31
   [27] include(::String) at ./client.jl:424
   [28] top-level scope at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/runtests.jl:168
   [29] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107
   [30] top-level scope at /home/runner/work/KernelFunctions.jl/KernelFunctions.jl/test/runtests.jl:61
   [31] include at ./boot.jl:328 [inlined]
   [32] include_relative(::Module, ::String) at ./loading.jl:1105
   [33] include(::Module, ::String) at ./Base.jl:31
   [34] include(::String) at ./client.jl:424
   [35] top-level scope at none:6
   [36] eval(::Module, ::Any) at ./boot.jl:330
   [37] exec_options(::Base.JLOptions) at ./client.jl:263
   [38] _start() at ./client.jl:460
```

on line https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/blob/7ce1c391c98b9f0e7a699c3555afdc2ec338d85b/test/chainrules.jl#L25

### PR DESCRIPTION
**Pull request by st--**
Aims to resolve #390 and #391

### CODE REVIEW

File: test/chainrules.jl [hunk 1]
```diff
@@ -21,7 +21,13 @@
     compare_gradient(:Zygote, [x, y]) do xy
         KernelFunctions.Sinus(r)(xy[1], xy[2])
     end
-    compare_gradient(:Zygote, [Q, x, y]) do xy
-        SqMahalanobis(xy[1])(xy[2], xy[3])
+    if VERSION < v"1.6"
```
Comment (devmotion) [inline test/chainrules.jl:24]: What's the reason for this check?

Comment (st--) [reply test/chainrules.jl:24]: The tests seemed to pass fine as is on 1.6, and I don't want to skip checks if I can avoid it.

Comment (devmotion) [reply test/chainrules.jl:24]: Sure, but how is the Julia version relevant here? It does not affect the version of Distances that is used, so why can't we use the same test for all Julia versions? It also seems tests fail on Julia 1.3 currently.

Comment (st--) [reply test/chainrules.jl:24]: Relevant because it _only_ fails in 1.3. It passes with 1.6 and 1.7.

Should we just skip the test for 1.3? Or raise julia compat to 1.4 (part of Ubuntu 20.04) or 1.6 (LTS)?

**Review by theogf — APPROVED** [review]
