### PR TITLE
Fix periodic kernel AD

### LINKED ISSUE #527: `PeriodicKernel` does not play with AD
I don't know since when this has been broken:
```julia
julia> using TestEnv; TestEnv.activate()
"/tmp/jl_cThCwu/Project.toml"

julia> using KernelFunctions, Zygote

julia> build_kernel(θ) = PeriodicKernel(; r = [θ.r])
build_kernel (generic function with 1 method)

julia> θ = (r = 1., )
(r = 1.0,)

julia> testfun(θ) = sum(kernelmatrix(build_kernel(θ), rand(10)))
testfun (generic function with 1 method)

julia> Zygote.gradient(testfun, θ)
ERROR: Mutating arrays is not supported -- called setindex!(Matrix{Float64}, ...)
This error occurs when you ask Zygote to differentiate operations that change
the elements of arrays in place (e.g. setting values with x .= ...)

Possible fixes:
- avoid mutating operations (preferred)
- or read the documentation and solutions for this error
  https://fluxml.ai/Zygote.jl/latest/limitations

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _throw_mutation_error(f::Function, args::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/lib/array.jl:88
  [3] (::Zygote.var"#555#556"{Matrix{Float64}})(#unused#::Nothing)
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/lib/array.jl:100
  [4] (::Zygote.var"#2659#back#557"{Zygote.var"#555#556"{Matrix{Float64}}})(Δ::Nothing)
    @ Zygote ~/.julia/packages/ZygoteRules/OgCVT/src/adjoint.jl:71
  [5] Pullback
    @ ~/.julia/packages/Distances/yhVAl/src/generic.jl:219 [inlined]
  [6] (::Zygote.Pullback{Tuple{typeof(Distances._pairwise!), KernelFunctions.Sinus{Float64}, Matrix{Float64}, Matrix{Float64}}, Any})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
  [7] Pullback
    @ ~/.julia/packages/Distances/yhVAl/src/generic.jl:287 [inlined]
  [8] (::Zygote.Pullback{Tuple{Distances.var"##pairwise!#2", Int64, typeof(StatsAPI.pairwise!), KernelFunctions.Sinus{Float64}, Matrix{Float64}, Matrix{Float64}}, Any})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
  [9] Pullback
    @ ~/.julia/packages/Distances/yhVAl/src/generic.jl:275 [inlined]
 [10] (::Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise!), KernelFunctions.Sinus{Float64}, Matrix{Float64}, Matrix{Float64}}, Any})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [11] Pullback
    @ ~/.julia/packages/Distances/yhVAl/src/generic.jl:330 [inlined]
 [12] (::Zygote.Pullback{Tuple{Distances.var"##pairwise#4", Int64, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [13] Pullback
    @ ~/.julia/packages/Distances/yhVAl/src/generic.jl:324 [inlined]
 [14] (::Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [15] Pullback
    @ ~/.julia/dev/KernelFunctions.jl/src/distances/pairwise.jl:16 [inlined]
 [16] (::Zygote.Pullback{Tuple{typeof(KernelFunctions.pairwise), KernelFunctions.Sinus{Float64}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,)}}, Tuple{Int64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,), Tuple{Int64}}}, Tuple{Int64}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:dims,), Tuple{Int64}}, Nothing, true}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.var"#2799#back#625"{Zygote.var"#619#623"{Vector{Float64}, Tuple{Colon, Int64}}}}})(Δ::Matrix{Float64})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [17] Pullback
    @ ~/.julia/dev/KernelFunctions.jl/src/matrix/kernelmatrix.jl:150 [inlined]
 [18] (::Zygote.Pullback{Tuple{typeof(kernelmatrix), PeriodicKernel{Float64}, Vector{Float64}}, Tuple{Zygote.var"#2881#back#688"{Zygote.var"#map_back#682"{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, 1, Tuple{Matrix{Float64}}, Tuple{Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Matrix{Tuple{Float64, Zygote.Pullback{Tuple{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Float64}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:κ, Zygote.Context{false}, KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, PeriodicKernel{Float64}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.kappa), PeriodicKernel{Float64}, Float64}, Tuple{Zygote.ZBack{ChainRules.var"#exp_pullback#1324"{Float64, ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}}}, Zygote.ZBack{ChainRules.var"#times_pullback2#1350"{Float64, Float64}}}}}}}}}}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.metric), PeriodicKernel{Float64}}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:r, Zygote.Context{false}, PeriodicKernel{Float64}, Vector{Float64}}}, Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus{Float64}}, Vector{Float64}}, Tuple{Zygote.ZBack{ChainRules.var"#fieldtype_pullback#421"}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.Sinus{Float64}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(convert), Type{Vector{Float64}}, Vector{Float64}}, Any}}}}}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.pairwise), KernelFunctions.Sinus{Float64}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,)}}, Tuple{Int64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,), Tuple{Int64}}}, Tuple{Int64}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:dims,), Tuple{Int64}}, Nothing, true}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.var"#2799#back#625"{Zygote.var"#619#623"{Vector{Float64}, Tuple{Colon, Int64}}}}}}})(Δ::FillArrays.Fill{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [19] Pullback
    @ ./REPL[5]:1 [inlined]
 [20] (::Zygote.Pullback{Tuple{typeof(testfun), NamedTuple{(:r,), Tuple{Float64}}}, Tuple{Zygote.var"#3027#back#782"{Zygote.var"#776#780"{Matrix{Float64}}}, Zygote.Pullback{Tuple{typeof(build_kernel), NamedTuple{(:r,), Tuple{Float64}}}, Tuple{Zygote.ZBack{ChainRules.var"#vect_pullback#1373"{1, Tuple{ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:r,), Tuple{Vector{Float64}}}, Type{PeriodicKernel}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.Pullback{Tuple{Type{NamedTuple{(:r,)}}, Tuple{Vector{Float64}}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:r,), Tuple{Vector{Float64}}}}, Tuple{Vector{Float64}}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:r,), Tuple{Vector{Float64}}}, Nothing, true}}}}}}, Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:r, Zygote.Context{false}, NamedTuple{(:r,), Tuple{Float64}}, Float64}}}}, Zygote.Pullback{Tuple{typeof(kernelmatrix), PeriodicKernel{Float64}, Vector{Float64}}, Tuple{Zygote.var"#2881#back#688"{Zygote.var"#map_back#682"{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, 1, Tuple{Matrix{Float64}}, Tuple{Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Matrix{Tuple{Float64, Zygote.Pullback{Tuple{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Float64}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:κ, Zygote.Context{false}, KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, PeriodicKernel{Float64}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.kappa), PeriodicKernel{Float64}, Float64}, Tuple{Zygote.ZBack{ChainRules.var"#exp_pullback#1324"{Float64, ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}}}, Zygote.ZBack{ChainRules.var"#times_pullback2#1350"{Float64, Float64}}}}}}}}}}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.metric), PeriodicKernel{Float64}}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:r, Zygote.Context{false}, PeriodicKernel{Float64}, Vector{Float64}}}, Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus{Float64}}, Vector{Float64}}, Tuple{Zygote.ZBack{ChainRules.var"#fieldtype_pullback#421"}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.Sinus{Float64}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(convert), Type{Vector{Float64}}, Vector{Float64}}, Any}}}}}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.pairwise), KernelFunctions.Sinus{Float64}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,)}}, Tuple{Int64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,), Tuple{Int64}}}, Tuple{Int64}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:dims,), Tuple{Int64}}, Nothing, true}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.var"#2799#back#625"{Zygote.var"#619#623"{Vector{Float64}, Tuple{Colon, Int64}}}}}}}, Zygote.ZBack{ChainRules.var"#rand_pullback#2182"{Tuple{Int64}}}}})(Δ::Float64)
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface2.jl:0
 [21] (::Zygote.var"#75#76"{Zygote.Pullback{Tuple{typeof(testfun), NamedTuple{(:r,), Tuple{Float64}}}, Tuple{Zygote.var"#3027#back#782"{Zygote.var"#776#780"{Matrix{Float64}}}, Zygote.Pullback{Tuple{typeof(build_kernel), NamedTuple{(:r,), Tuple{Float64}}}, Tuple{Zygote.ZBack{ChainRules.var"#vect_pullback#1373"{1, Tuple{ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:r,), Tuple{Vector{Float64}}}, Type{PeriodicKernel}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.Pullback{Tuple{Type{NamedTuple{(:r,)}}, Tuple{Vector{Float64}}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:r,), Tuple{Vector{Float64}}}}, Tuple{Vector{Float64}}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:r,), Tuple{Vector{Float64}}}, Nothing, true}}}}}}, Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:r, Zygote.Context{false}, NamedTuple{(:r,), Tuple{Float64}}, Float64}}}}, Zygote.Pullback{Tuple{typeof(kernelmatrix), PeriodicKernel{Float64}, Vector{Float64}}, Tuple{Zygote.var"#2881#back#688"{Zygote.var"#map_back#682"{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, 1, Tuple{Matrix{Float64}}, Tuple{Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Matrix{Tuple{Float64, Zygote.Pullback{Tuple{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Float64}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:κ, Zygote.Context{false}, KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, PeriodicKernel{Float64}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.kappa), PeriodicKernel{Float64}, Float64}, Tuple{Zygote.ZBack{ChainRules.var"#exp_pullback#1324"{Float64, ChainRulesCore.ProjectTo{Float64, NamedTuple{(), Tuple{}}}}}, Zygote.ZBack{ChainRules.var"#times_pullback2#1350"{Float64, Float64}}}}}}}}}}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.var"#68#69"{PeriodicKernel{Float64}}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.metric), PeriodicKernel{Float64}}, Tuple{Zygote.var"#2184#back#303"{Zygote.var"#back#302"{:r, Zygote.Context{false}, PeriodicKernel{Float64}, Vector{Float64}}}, Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{KernelFunctions.Sinus{Float64}}, Vector{Float64}}, Tuple{Zygote.ZBack{ChainRules.var"#fieldtype_pullback#421"}, Zygote.var"#2214#back#313"{Zygote.Jnew{KernelFunctions.Sinus{Float64}, Nothing, false}}, Zygote.Pullback{Tuple{typeof(convert), Type{Vector{Float64}}, Vector{Float64}}, Any}}}}}}}, Zygote.Pullback{Tuple{typeof(KernelFunctions.pairwise), KernelFunctions.Sinus{Float64}, Vector{Float64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,)}}, Tuple{Int64}}, Tuple{Zygote.Pullback{Tuple{Type{NamedTuple{(:dims,), Tuple{Int64}}}, Tuple{Int64}}, Tuple{Zygote.var"#2224#back#315"{Zygote.Jnew{NamedTuple{(:dims,), Tuple{Int64}}, Nothing, true}}}}}}, Zygote.Pullback{Tuple{typeof(Core.kwcall), NamedTuple{(:dims,), Tuple{Int64}}, typeof(StatsAPI.pairwise), KernelFunctions.Sinus{Float64}, Matrix{Float64}}, Any}, Zygote.var"#2017#back#204"{typeof(identity)}, Zygote.var"#2799#back#625"{Zygote.var"#619#623"{Vector{Float64}, Tuple{Colon, Int64}}}}}}}, Zygote.ZBack{ChainRules.var"#rand_pullback#2182"{Tuple{Int64}}}}}})(Δ::Float64)
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface.jl:45
 [22] gradient(f::Function, args::NamedTuple{(:r,), Tuple{Float64}})
    @ Zygote ~/.julia/packages/Zygote/XJ8pP/src/compiler/interface.jl:97
 [23] top-level scope
    @ REPL[6]:1
```

### PR DESCRIPTION
**Pull request by simsurace**
This PR reactivates the AD tests for the periodic kernel and introduces `rrules` to make them pass.
Fixes #527

### CODE REVIEW

File: test/basekernels/periodic.jl [hunk 1]
```diff
@@ -15,7 +15,6 @@
     TestUtils.test_interface(PeriodicKernel(; r=[0.9, 0.9]), ColVecs{Float64})
     TestUtils.test_interface(PeriodicKernel(; r=[0.8, 0.7]), RowVecs{Float64})
 
-    # test_ADs(r->PeriodicKernel(r =exp.(r)), log.(r), ADs = [:ForwardDiff, :ReverseDiff])
-    @test_broken "Undefined adjoint for Sinus metric, and failing randomly for ForwardDiff and ReverseDiff"
+    test_ADs(r -> PeriodicKernel(; r=exp.(r)), log.(r))
```
Comment (willtebbutt) [inline test/basekernels/periodic.jl:18]: Could you please utilise ChainRulesTestUtils.jl here to directly unit test the `rrule`s that you've added? `test_ADs` is really designed for integration testing the entire pipeline, rather than unit-testing individual rules, and we should typically do both.

File: src/chainrules.jl [hunk 2]
```diff
@@ -112,15 +112,108 @@ end
...
+        Δ = unthunk(z̄)
+        n = size(x, dims)
+        x̄ = zero(x)
+        r̄ = zero(d.r)
+        if dims == 1
+            for j in 1:n, i in 1:n
+                xi = view(x, i, :)
+                xj = view(x, j, :)
+                ds = twoπ .* Δ[i, j] .* sinpi.(xi .- xj) .* cospi.(xi .- xj) ./ d.r .^ 2
+                r̄ .-= 2 .* Δ[i, j] .* sinpi.(xi .- xj) .^ 2 ./ d.r .^ 3
```
Comment (devmotion) [inline src/chainrules.jl:138]: This assumes that rbar supports `setindex!` which is not true in general.

File: test/basekernels/periodic.jl (hunk 1 above)
Comment (simsurace) [reply test/basekernels/periodic.jl:18]: I think this makes a lot of sense, but I want to note that none of the other rules seem to be tested in this way.

Comment (willtebbutt) [reply test/basekernels/periodic.jl:18]: This is probably a legacy issue on our part -- probably when we wrote the tests CRTU wasn't as mature as it is now. We should probably fix this, and ensure that all of our rules are properly tested.

Comment (simsurace) [reply test/basekernels/periodic.jl:18]: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/532

Comment (simsurace) [reply test/basekernels/periodic.jl:18]: I will add tests for this rule here, the others will be done in a separate PR.

Comment (willtebbutt) [reply test/basekernels/periodic.jl:18]: Yes, definitely don't add those extra tests in this PR -- sorry if it sounded like I was asking you to. It was not my intention!

**Comment by simsurace** [comment]
Ok, I added ChainRulesTestUtils tests for normal and static arrays. The static case is certainly not optimal, but I don't have the capacity to think of how to rewrite the rules to be non-mutating.

If anyone knows off-hand how to do this, feel free to make a suggestion.

**Comment by simsurace** [comment]
@willtebbutt Could we merge this? The comment regarding the generality of the rule does not I apply (I believe) because of the concrete type of the field of `Sinus`.

**Comment by simsurace** [comment]
@JuliaRegistrator register()

File: src/chainrules.jl [hunk 3]
```diff
@@ -112,15 +112,113 @@ end
 function ChainRulesCore.rrule(s::Sinus, x::AbstractVector, y::AbstractVector)
     d = x - y
     sind = sinpi.(d)
-    abs2_sind_r = abs2.(sind) ./ s.r
+    abs2_sind_r = abs2.(sind) ./ s.r .^ 2
     val = sum(abs2_sind_r)
-    gradx = twoπ .* cospi.(d) .* sind ./ (s.r .^ 2)
+    gradx = twoπ .* cospi.(d) .* sind ./ s.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:117]: This can be simplified to
```suggestion
    abs2_sind_r = (sinpi.(d) ./ s.r) .^ 2
    val = sum(abs2_sind_r)
    gradx = π .* cospi.(2 .* d) ./ s.r .^ 2
```

File: src/chainrules.jl [hunk 4]
```diff
@@ -112,15 +112,113 @@ end
...
+    function pairwise_pullback(z̄)
+        Δ = unthunk(z̄)
+        n = size(x, dims)
+        x̄ = collect(zero(x))
+        r̄ = zero(d.r)
+        if dims == 1
+            for j in 1:n, i in 1:n
+                xi = view(x, i, :)
+                xj = view(x, j, :)
+                ds = twoπ .* Δ[i, j] .* sinpi.(xi .- xj) .* cospi.(xi .- xj) ./ d.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:139]:
```suggestion
                ds = π .* Δ[i, j] .* cospi.(2 .* (xi .- xj)) ./ d.r .^ 2
```

File: src/chainrules.jl [hunk 5]
```diff
@@ -112,15 +112,113 @@ end
...
+                r̄ .-= 2 .* Δ[i, j] .* sinpi.(xi .- xj) .^ 2 ./ d.r .^ 3
+                x̄[i, :] += ds
+                x̄[j, :] -= ds
```
Comment (devmotion) [inline src/chainrules.jl:142]: To save a few allocations this should be
```suggestion
                x̄[i, :] .+= ds
                x̄[j, :] .-= ds
```
shouldn't it?

File: src/chainrules.jl [hunk 6]
```diff
@@ -112,15 +112,113 @@ end
...
+            end
+        elseif dims == 2
+            for j in 1:n, i in 1:n
+                xi = view(x, :, i)
+                xj = view(x, :, j)
+                ds = twoπ .* Δ[i, j] .* sinpi.(xi .- xj) .* cospi.(xi .- xj) ./ d.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:148]:
```suggestion
                ds = π .* Δ[i, j] .* cospi.(2 .* (xi .- xj)) ./ d.r .^ 2
```

File: src/chainrules.jl [hunk 7]
```diff
@@ -112,15 +112,113 @@ end
...
+                r̄ .-= 2 .* Δ[i, j] .* sinpi.(xi .- xj) .^ 2 ./ d.r .^ 3
+                x̄[:, i] += ds
+                x̄[:, j] -= ds
```
Comment (devmotion) [inline src/chainrules.jl:151]:
```suggestion
                x̄[:, i] .+= ds
                x̄[:, j] .-= ds
```

File: src/chainrules.jl [hunk 8]
```diff
@@ -112,15 +112,113 @@ end
...
+        n = size(x, dims)
+        m = size(y, dims)
+        x̄ = collect(zero(x))
+        ȳ = collect(zero(y))
+        r̄ = zero(d.r)
+        if dims == 1
+            for j in 1:m, i in 1:n
+                xi = view(x, i, :)
+                yj = view(y, j, :)
+                ds = twoπ .* Δ[i, j] .* sinpi.(xi .- yj) .* cospi.(xi .- yj) ./ d.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:176]:
```suggestion
                ds = π .* Δ[i, j] .* cospi.(2 .* (xi .- yj)) ./ d.r .^ 2
```

File: src/chainrules.jl [hunk 9]
```diff
@@ -112,15 +112,113 @@ end
...
+                r̄ .-= 2 .* Δ[i, j] .* sinpi.(xi .- yj) .^ 2 ./ d.r .^ 3
+                x̄[i, :] += ds
+                ȳ[j, :] -= ds
```
Comment (devmotion) [inline src/chainrules.jl:179]:
```suggestion
                x̄[i, :] .+= ds
                ȳ[j, :] .-= ds
```

File: src/chainrules.jl [hunk 10]
```diff
@@ -112,15 +112,113 @@ end
...
+            end
+        elseif dims == 2
+            for j in 1:m, i in 1:n
+                xi = view(x, :, i)
+                yj = view(y, :, j)
+                ds = twoπ .* Δ[i, j] .* sinpi.(xi .- yj) .* cospi.(xi .- yj) ./ d.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:185]:
```suggestion
                ds = π .* Δ[i, j] .* cospi.(2 .* (xi .- yj)) ./ d.r .^ 2
```

File: src/chainrules.jl [hunk 11]
```diff
@@ -112,15 +112,113 @@ end
...
+                r̄ .-= 2 .* Δ[i, j] .* sinpi.(xi .- yj) .^ 2 ./ d.r .^ 3
+                x̄[:, i] += ds
+                ȳ[:, j] -= ds
```
Comment (devmotion) [inline src/chainrules.jl:188]:
```suggestion
                x̄[:, i] .+= ds
                ȳ[:, j] .-= ds
```

File: src/chainrules.jl [hunk 12]
```diff
@@ -112,15 +112,113 @@ end
...
+    function colwise_pullback(z̄)
+        Δ = unthunk(z̄)
+        n = size(x, 2)
+        x̄ = collect(zero(x))
+        ȳ = collect(zero(y))
+        r̄ = zero(d.r)
+        for i in 1:n
+            xi = view(x, :, i)
+            yi = view(y, :, i)
+            ds = twoπ .* Δ[i] .* sinpi.(xi .- yi) .* cospi.(xi .- yi) ./ d.r .^ 2
```
Comment (devmotion) [inline src/chainrules.jl:211]:
```suggestion
            ds = π .* Δ[i] .* cospi.(2 .* (xi .- yi)) ./ d.r .^ 2
```

File: src/chainrules.jl [hunk 13]
```diff
@@ -112,15 +112,113 @@ end
...
+            r̄ .-= 2 .* Δ[i] .* sinpi.(xi .- yi) .^ 2 ./ d.r .^ 3
+            x̄[:, i] += ds
+            ȳ[:, i] -= ds
```
Comment (devmotion) [inline src/chainrules.jl:214]:
```suggestion
            x̄[:, i] .+= ds
            ȳ[:, i] .-= ds
```

**Review by devmotion — COMMENTED** [review]
A few additional suggestions.

File: src/chainrules.jl (hunk 3 above)
Comment (simsurace) [reply src/chainrules.jl:117]: Thanks! I will start a follow-up PR.

File: src/chainrules.jl (hunk 4 above)
Comment (simsurace) [reply src/chainrules.jl:139]: I will start a follow-up PR
